# Generated by Django 3.2.5 on 2021-07-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('us_500', models.CharField(max_length=30)),
                ('us_tech_100', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
